trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: chmod +x gradlew
  displayName: 'Grant execute permission for gradlew'

- script: ./gradlew assembleDebug
  displayName: 'Build with Gradle'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'app/build/outputs'
    ArtifactName: 'apk-debug'
    publishLocation: 'container'